-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "citext";

-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "name" SET DATA TYPE CITEXT,
ALTER COLUMN "slug" SET DATA TYPE CITEXT;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "slug" SET DATA TYPE CITEXT;

-- AlterTable
ALTER TABLE "Tag" ALTER COLUMN "name" SET DATA TYPE CITEXT,
ALTER COLUMN "slug" SET DATA TYPE CITEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE CITEXT,
ALTER COLUMN "username" SET DATA TYPE CITEXT;
